# Generated by Django 3.2.3 on 2021-06-02 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arenda_date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('arenda_date_finish', models.DateTimeField(verbose_name='Дата окончания')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flat.flat', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['arenda_date_start'],
            },
        ),
    ]
